# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=4)),
                ('major', models.CharField(max_length=50)),
                ('stu_num', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
